accounts/urls.py
from django.urls import path, include
from .views import SignUpView, profile

app_name = 'accounts'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/<int:user_id>/', profile, name='profile')
]

blog/urls.py
from django.urls import path
from .views import (
    BlogListView,
    BlogDetailView,
    BlogNewView,
    BlogEditView,
    BlogDeleteView,
)

app_name = 'blog'
urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('post_detail/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),
    path('post/new/', BlogNewView.as_view(), name='post_new'),
    path('post/edit/<int:pk>/', BlogEditView.as_view(), name='post_edit'),
    path('post/delete/<int:pk>/', BlogDeleteView.as_view(), name='post_delete'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)

# Create your models here.

blog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.auth import get_user_model


class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[str(self.id)])

accounts/forms.py
from django import forms
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'email', 'age')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'age')

accounts/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CustomUserCreationForm
from .models import CustomUser
from django.shortcuts import render


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('login')


def profile(request, user_id):
    user = CustomUser.objects.get(id=user_id)
    context = {'user': user}
    return render(request, 'accounts/profile.html', context)

blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin


class BlogListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/home.html'
    login_url = 'login'


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    login_url = 'login'


class BlogNewView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'blog/post_new.html'
    fields = ['title', 'text']
    login_url = 'login'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class BlogEditView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'blog/post_edit.html'
    fields = ['title', 'text']
    login_url = 'login'


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'blog/post_delete.html'
    success_url = reverse_lazy('blog:home')
    login_url = 'login'

accounts/templates/accounts/profile.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1>{{ user.username }}</h1>
    {% if user.age %}
        <h1>{{ user.age }} years old</h1>
    {% endif %}
    {% if user.email %}
        <h1>Email: {{ user.email }}</h1>
    {% endif %}
    <a href="{% url 'password_change' %}">Change password</a>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'blog/base.html' %}
{% block title %}Sign Up{% endblock title %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
{% endblock content %}

blog/templates/blog/base.html
<html>
    <head>
        <title>Django blog</title>
    </head>
    <body>
        <header>
            {% block title %}
            {% endblock title %}
            <div class="nav-left">
                <h1><a href="{% url 'blog:home' %}">Django blog</a></h1>
            </div>
            <div class="nav-right">
                <a href="{% url 'blog:post_new' %}">New Blog post</a>
            </div>
        </header>
        {% if user.is_authenticated %}
            <p>Hi, <a href="{% url 'accounts:profile' user.id %}">{{ user.username }}</a></p>
            <a href="{% url 'logout' %}">Log Out</a>
        {% else %}
            <p>You are not logged in</p>
            <a href="{% url 'login' %}">Log in</a>
            <a href="{% url 'accounts:signup' %}">Sign Up</a>
        {% endif %}
        <div>
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %}
  {% for post in object_list %}
    <div class="post-entry">
      <h2><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h2>
      <p>{{ post.text }}</p>
    </div>
  {% endfor %}
{% endblock content %}

blog/templates/blog/post_delete.html
{% extends 'blog/base.html' %}
{% block content %}
  <h1>Delete post</h1>
  <form action="{% url 'blog:post_delete' post.pk %}" method="post">
    {% csrf_token %}
    <p>Are you sure want delete "{{ post.title }}" ?</p>
    <input type="submit" value="Delete" />
  </form>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
  <div class="post-entry">
    <h2>{{ post.title }}</h2>
    <p>{{ post.text }}</p>
  </div>
  <a href="{% url 'blog:post_edit' post.pk %}">Edit post</a>
  <a href="{% url 'blog:post_delete' post.pk %}">Delete post</a>
{% endblock content %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% block content %}
    <form action="{% url 'blog:post_edit' post.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit", value="Confirm" />
    </form>
{% endblock content %}

blog/templates/blog/post_new.html
{% extends 'blog/base.html' %}
{% block content %}
  <form action="{% url 'blog:post_new' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
  </form>
{% endblock content %}